site_name: GitHub Projects for Jakob Bagterp
site_url: https://jakob-bagterp.github.io/
site_description: Python packages and tools that makes life a little easier.
site_author: Jakob Bagterp
copyright: Copyright © 2025 - , Jakob Bagterp. All Rights Reserved.
repo_url: https://github.com/jakob-bagterp/jakob-bagterp.github.io
nav:
  - Home:
    - index.md

theme:
  name: material
  custom_dir: docs/assets/overrides
  features:
    - search.suggest
    - search.highlight
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.path
    - navigation.indexes
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/eye
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/eye-outline
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - footnotes
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      name: IndexNow for Python on GitHub
      link: https://github.com/jakob-bagterp/index-now-for-python
    - icon: fontawesome/brands/linkedin
      name: Jakob Bagterp on LinkedIn
      link: https://www.linkedin.com/in/jakobbagterp/
    - icon: fontawesome/brands/instagram
      name: Jakob Bagterp on Instagram
      link: https://www.instagram.com/bagterp_photography/
  analytics:
    provider: google
    property: G-998DJ8EJPL
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thank you for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thank you for your feedback! Help us improve this page by using our
            <a href="https://github.com/jakob-bagterp/index-now-for-python/issues/new/?title=[Feedback]+{title}+-+{url}"
            target="_blank" rel="noopener">
            feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      js_files:
          - js/timeago_mkdocs_material.js
      css_files:
          - css/timeago.css
          - assets/_mkdocstrings.css

watch:
  - src

dev_addr: 127.0.0.1:8005
